AMLOGICRDK-53 : Monthly feature branch upgrade
Upgrade to tip of rdk-next

REFPLTB-1464,REFPLTV-1156 : Blocklist mechanism for Nonroot process causing issues on RPI-B and Turris

Reason for change: Added add-non-root-user-group.inc to create new user non-root
Test procedure: Tested in local build
Risks: None

Signed-off-by: kpandu549 <keerthana_pandurangan@comcast.com>
Change-Id: Ib70244bd97a9813c7d1128d654391e8c27dfcfbc

Enable SSL 1.1.1 for dunfell builds

This is required after meta-rdk/65062 is merged.

Change-Id: Ie69e620f37bcefaed90017fdc731e4086c75d370

Re-enable ccsp-logagent in BB builds

It has been removed by meta-rdk/65342

Change-Id: I0363c82d540e097f4d1f85c0015d386afe823e6e

Add waymetric to build

The waymetric recipe has been added recently by meta-rdk-video/65073

Change-Id: Ie76d5a44242c308a3f3c568e0f126c407315ea29

Add waymetric external source definition

Change-Id: Ic276c9d4b85b2c59b177d220527f1d173b49d5aa

REFPLTV-1113 : Switch to stable version

Reason for change: Matching with the stable version of comcast
Test Procedure: Test Dial features
Risks: Low

Signed-off-by: Simon Chung <simon.c.chung@accenture.com>
Change-Id: If202415b4e7f1c5b085d07d1848b27d34f2c0a2b

Re-enable xdialserver external source build

Change-Id: I0e941d34ded1d65437594cd27a38f874a5270d0a

Disable tdk external source build

Change-Id: I5fc26693cc9dd72a1886973bd4e4b3814216363d

TDK-4717: TDK-V Git repo size reduction

Reason for change: Updating rdk-external-src.inc with latest TDKV repo check
Test Procedure:Verify TDK builds are success
Risks: None
Signed-off-by: Pari Tholkappian <Pari_Tholkappian@comcast.com
Change-Id: Ia1fb1edbac0ce27248a3ae551b2bb97ea5ab253b

Move enabling of waymetric to RPi layer

Change-Id: Ia3455d85fed602b275daa45f1d8cb3d9c0903334

Enable md4 (bb) and rc4 (camera) in openssl_1.1.1%

BB hostapd fails to build without md4
| ../src/crypto/crypto_openssl.c:190: error: undefined reference to 'EVP_md4'

Camera rms fails to build without rc4
| /home/jenkins/jenkinsroot/workspace/build-rpi-camera/EXEC_0/rdkc/components/opensource/rms/sources/common/include/utils/misc/crypto.h:94:3: error: 'RC4_KEY' has not been declared
|    94 |   RC4_KEY *rc4keyIn, RC4_KEY *rc4keyOut);
|       |   ^~~~~~~
| /home/jenkins/jenkinsroot/workspace/build-rpi-camera/EXEC_0/rdkc/components/opensource/rms/sources/common/include/utils/misc/crypto.h:94:22: error: 'RC4_KEY' has not been declared
|    94 |   RC4_KEY *rc4keyIn, RC4_KEY *rc4keyOut);
|       |

Change-Id: I812b1b8a884f76de37209180868ceafbc15065ab

Add dunfell BBMASK for morty breakpad recipe

The breakpad recipe in meta-cmf is for morty only (git instead of svn version)
Dunfell should use the default breakpad recipe in meta-openembedded

Change-Id: I0098202ea5fd560f94fb51757a17bc698349ffd3

Add breakpad recipe append to create missing dir

Fix problems with Fatal error: can't create src/processor/stackwalk_common.o: No such file or directory

Change-Id: Ie87fb1515a80e3596d9a8e13a3cf9c7635c830e4

Enable meta-spdxscanner layer if it is present

Change-Id: Iad6148fa30e053a6e30c7a926593b6642f9da81f

Switch to use https protocol for GitHub

fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Change-Id: I3febbd4e1693e98964318e6ce0292acce742e465

Switch to use https protocol for GitHub

fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Change-Id: I635ef79405638b4a6d537ca6b34fe0e33f3186dc

Add xxx.inc to fix Uninative failure

ERROR: Uninative selected but not configured correctly, please set UNINATIVE_CHECKSUM[x86_64]
caused by meta-rdk/+/66394
where the yocto-uninative.inc include has been removed, and should have been moved to
the new xxx.inc file.

Change-Id: I9346b59785cd63406b4947e45f834ef15ef3f642

Add syslog-ng-config-gen.bbclass and breakpad-logmapper.bbclass

It is needed after cmf-update-RDK-34349-stable2-20220114 topic changes are merged.

Change-Id: I4a4efa7c5322b064252a1c8fb5512d4833151d78

Add missing libbsd dependency to bluealsa

It is needed to fix intermitten build errors

Change-Id: Ie2c969d6879d86e516868509ec0adeecd6a221e7

Enable meta-srcmap instead of meta-spdxscanner

Change-Id: I44498a0bc3414e91a8fbd03323009f9ce20f6c8b

Update github.com/xmidt-org SRC_URI overrides

It is needed after meta-rdk-ext/66864 is merged.

Change-Id: I997147225e7c1262a65c93a50c3f100f3592826a

Enable alexa skillmapper external source build

Change-Id: I72469bbd86d1a7d9972c3c552725c68f64dae81e

Enable pwstream external source build

Change-Id: I90d1a410bc9684afbe466eb5995c2766b5be4827

RDK-34449: Dobby v3.2.0 release

Reason for change: Federated Dobby Release v3.2.0

Test Procedure: Test containerised app launch and lifecycle

Risks: Low
Signed-off-by: Simon Chung <simon.c.chung@accenture.com>
Change-Id: Ieaa3d1238f4420e27ffe8c720e7c75a0d518572a

Enable gst-svp-ext extsrc build

Change-Id: I1b6c123cb51358d4059a652eb6d7e530e3a06737

Fix bluealsa SRCREV

to Fix premature IO threads startup for oFono service
Latest commits added dependency on spandsp
which causes build failures.

Change-Id: I68932527bff57ed06fe361fa85806422251117c4

Disable uninative, yocto server for the uninative SDK fails to fetch intermittenly

Change-Id: I294cad2aeabc89379f33d530d3dfc8b1ede28262

Revert "Re-enable ccsp-logagent in BB builds"

This reverts commit cccc56be4fa5184b9b17cbba8e00850f4541f427.

Reason for revert: ccsp-logagent is no longer buildable after cmf-update-RDKB-39178_stable2-20220226 topic changes are merged.

Change-Id: Icf7ff3bf0c2a14518d4b5a2815b807b8ff665102

Added add-non-root-user-group.inc to create new user non-root

for rdk-generic-hybrid-dtv-image from meta-dtvkit-bcm

Change-Id: I1d0060873d5638c76f8207db82cc49a78dad1fcf

Added add-non-root-user-group.inc to create new user non-root

for rdk-generic-hybrid-image

Change-Id: Iff7bc4e24e77b0cb4d84239b7bc5402325314cb4

Add breakpad dependency in breakpad-wrapper for camera and extender

It is needed to fix build issues:
| ../git/breakpad_wrapper.cpp:20:10: fatal error: client/linux/handler/exception_handler.h: No such file or directory
|    20 | #include client/linux/handler/exception_handler.h
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.

Change-Id: I2e8d2273a1f182cfd8a48d6e00e0488811b5c9a4

Add telemetry dependency to dropbear

The dependency is added by meta-rdk-ext/+/68909

Change-Id: I2aa429ee582a6ccb50d6d4d9b74e9479e1b7d2b1

Add BBMASK for ccsp-one-wifi

The temporary bbmask is needed until the ccsp-one-wifi component is opensourced.
Caused by meta-rdk-broadband/+/68998

Change-Id: I44411b3bc8063afbf4e4eac1c525d8888453cbda