Add xxx.inc to fix Uninative failure
ERROR: Uninative selected but not configured correctly, please set UNINATIVE_CHECKSUM[x86_64]
caused by meta-rdk/+/66394
where the yocto-uninative.inc include has been removed, and should have been moved to
the new xxx.inc file.

Change-Id: I9346b59785cd63406b4947e45f834ef15ef3f642