Add breakpad dependency in breakpad-wrapper for camera and extender
It is needed to fix build issues:
| ../git/breakpad_wrapper.cpp:20:10: fatal error: client/linux/handler/exception_handler.h: No such file or directory
|    20 | #include client/linux/handler/exception_handler.h
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.

Change-Id: I2e8d2273a1f182cfd8a48d6e00e0488811b5c9a4